### PR TITLE
Fix sample links

### PR DESCRIPTION
**Pull request by gramidt**
**Problem:**
The sample links in the README are incorrect.

**Solution:**
Update the link.

**Validation:**
Opened link.

**Type of change:**
- [ ] Feature work
- [] Bug fix
- [X] Documentation
- [ ] Engineering change
- [ ] Test
- [ ] Logging/Telemetry

**Risk**:
- [ ] High – Errors could cause MAJOR regression of many scenarios. (Example: new large features or high level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios. (Example: somewhat complex bug fixes, small new features)
- [X] Small – No issues are expected. (Example: Very small bug fixes, string changes, or configuration settings changes)

**Work Item links**:
N/A

**Documentation Links**:
N/A

### CODE REVIEW

**Review by symorton — APPROVED** [review]

**Comment by gramidt** [comment]
@symorton - Are there any additional steps for getting this merged? I have more PRs that I may be submitting soon and want to ensure I know and account for the proper process.

Thank you again for all of your help!

**Comment by gramidt** [comment]
Friendly reminder, @symorton. :) ☝️

**Comment by symorton** [comment]
> Friendly reminder, @symorton. :) ☝️

nope no additional steps! All checks pass, so go right ahead :)

**Comment by gramidt** [comment]
Thank you so much, @symorton! I sincerely appreciate it.

After approval, what is the typical time for changes to be merged?

**Pull request closed without merging**
